repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v2.2.3
    hooks:
      - id: end-of-file-fixer
      - id: flake8
        exclude: "configs"
      - id: trailing-whitespace
  - repo: "https://github.com/asottile/seed-isort-config"
    rev: v1.9.2
    hooks:
      - id: seed-isort-config
  - repo: "https://github.com/pre-commit/mirrors-isort"
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: "https://github.com/ambv/black"
    rev: stable
    hooks:
      - id: black