language: python
os: linux
cache: pip
services:
  - redis
  - memcached
python:
  - "3.6"
  - "3.7"
  - "3.8"
stages:
  - test
  - benchmark
install:
  - pip install -e ".[dev]" -i https://mirrors.aliyun.com/pypi/simple
script:
  - flake8 src tests
  - pytest --benchmark-skip
after_success:
  - bash <(curl -s https://codecov.io/bash)
jobs:
  include:
    - stage: benchmark
      name: benchmark
      script:
        - >
          pytest --benchmark-only --no-cov
          --benchmark-min-time=0.2 --benchmark-max-time=0.5
          --benchmark-min-rounds=20 --benchmark-calibration-precision=50
          --benchmark-disable-gc --benchmark-group-by=func
          --benchmark-columns=min,max,mean,ops,rounds,iterations
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  username: ${DEPLOY_PYPI_USER}
  password: ${DEPLOY_PYPI_PASSWORD}
  on:
    tags: true
    branch: master
