sudo: false
language: python
cache: pip
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
install:
  - pip install -e ".[dev]"
script:
  - pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
