sudo: false
language: python
cache: pip
services:
  - redis-server
  - memcached
matrix:
  include:
    - python: 3.6
    - python: 3.7
install:
  - pip install -e ".[dev]"

stages:
  - test
  - benchmark
jobs:
  include:
    - stage: test
      name: test
      script:
        - flake8 src tests
        - pytest --benchmark-skip
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: benchmark
      name: benchmark
      script:
        - pytest --benchmark-only --no-cov --benchmark-min-rounds=20 --benchmark-calibration-precision=50 --benchmark-disable-gc
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: ${DEPLOY_PYPI_USER}
  password: ${DEPLOY_PYPI_PASSWORD}
  on:
    tags: true
    branch: master
