name: test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  pytest:
    name: Run pytest
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      memcached:
        image: memcached
        ports:
          - 11211:11211
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install libmemcached-dev
          python -m pip install --upgrade pip
          pip install -e ".[dev]" -i https://mirrors.aliyun.com/pypi/simple
      - name: Lint with flake8
        run: flake8 src tests
      - name: Test with pytest
        run: pytest --benchmark-skip
      - name: Upload coverage to Codecov
        if: success() && matrix.python-version == 3.7
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
